### ISSUE TITLE
input files

### ISSUE THREAD

**Issue by alexlipa91** [ruhan/toyslim#1]
Hi there,
I am trying to use your code for cSLIM and I always get some error about matrix dimensionality.
Can you specify the expected format of the input matrices?
I was providing a train user-rating-matrix [u,i] and a item-content-matrix [i,f]
I also tried to transpose the item-content-matrix to make it [f,i], but I always get ValueError: blocks[:,0] has incompatible column dimensions

**Comment by ruhan** [comment]
Hi Alex!

You should provide a user-rating [u, i] and an item-content [i, f] as you've done.

You have to take care of the numbers that you pass: they should be normalized to start on one.

Beyond that, the problem that you are getting normally is related to errors in the relations between both matrixes, the number of items in both should be equal. Are you checking it?

Anyways, I have a new version of the code of ToySLIM and I will update it ASAP.

**Comment by ruhan** [comment]
Hi Alex, I checked out and see that the new version was already on, sorry by that.

Do you checked the matrix dimensionalities?

If it is possible to you, could you share the datasets with me? Using it would be more simple to reproduce and fix the error.

Hope you the best.

**Comment by alexlipa91** [comment]
Hi Ruhan,

sorry if I hadn't replied before. 
I fixed the error. First, I was using a csv file and then I had also to make the indexes starting from 1.
Anyway, thanks.
I have another question for you, let's say more theoretical. I'm using this algorithm for item ranking predictions and I get very bad results in measures like precision and recall. 
Do you think it is normal because SSLIM optimizes sum of squares or maybe I have to play a bit with the parameters in order to significantly improve the results?

**Comment by ruhan** [comment]
Oh, man... the algorithm is very sensible to parameters, so you will need to optimize them before getting good results. You might use cross validation to do that. SSLIM will probably return good predictions if you optimize their parameters, so do not give up :)

I will close that issue.
