### ISSUE TITLE
Problem about certain line

### ISSUE THREAD

**Issue by yudi-mars** [ruhan/toyslim#2]
https://github.com/ruhan/toyslim/blob/008abbac61246d1845d58afda44584be88b72bda/slim.py#L6

Hi,
where is the `parse_args` and `tsv_to_matrix` in `util` folder?

**Comment by ruhan** [comment]
Hi @AmazingDD ,

These functions are in util/__init__.py file.

[https://github.com/ruhan/toyslim/blob/008abbac61246d1845d58afda44584be88b72bda/util/__init__.py](url)

Let me know if you have any other difficulties.
